### PR TITLE
Blog app - integration specs for views and fix n+1 problems

### PR DESCRIPTION
**Pull request by MozamelJawad**
**Hi Reviewer 👋**
<hr />

**In this PR, we worked on the following features:** 

- [x] Solved the N+1 problem is solved when fetching all posts and their comments for a user
- Before: 
before
- After: 
after

<hr />

**Integration specs**
- Used Capybara to write integration tests for each view in the project.
- [x] User index page:
  - I can see the username of all other users.
  - I can see the profile picture for each user.
  - I can see the number of posts each user has written.
  - When I click on a user, I am redirected to that user's show page.
- [x] user show page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see the user's bio.
  - I can see the user's first 3 posts.
  - I can see a button that lets me view all of a user's posts.
  - When I click a user's post, it redirects me to that post's show page.
  - When I click to see all posts, it redirects me to the user's post's index page.
- [x] User post index page:
  - I can see the user's profile picture.
  - I can see the user's username.
  - I can see the number of posts the user has written.
  - I can see a post's title.
  - I can see some of the post's body.
  - I can see the first comments on a post.
  - I can see how many comments a post has.
  - I can see how many likes a post has.
  - I can see a section for pagination if there are more posts than fit on the view.
  - When I click on a post, it redirects me to that post's show page.
- [x] Post show page:
  - I can see the post's title.
  - I can see who wrote the post.
  - I can see how many comments it has.
  - I can see how many likes it has.
  - I can see the post body.
  - I can see the username of each commentor.
  - I can see the comment each commentor left.

### CODE REVIEW

**Review by LionRouge1 — COMMENTED** [review]
Hi **Team**, 

done

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

According to your PR description, I think you have submitted a wrong project for this activity. Kindly make sure you use the button in front of the activity in your dashboard.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MozamelJawad** [comment]
Thanks for your feedback, I submit it again for the correct project.

**Review by LionRouge1 — CHANGES_REQUESTED** [review]
Hi @MozamelJawad & @fatmahussein, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

almost

## Highlights
- Use Capybara gem in `Gemfile` for Integration test :heavy_check_mark: 
- Tested all the features requested in the project requirement :heavy_check_mark: 
- Solve **N+1** problem when fetching all the posts :x:

## Required Changes ♻️
- [ ] Nice work adding the screenshots of the logs before and after the fix to the PR description :clap: However the N+1 problem persists when fetching all the posts. Kindly make sure you solve the **N+1** problem to improve your app performance.

  **HIT:** use `@posts = @user.posts.includes(:comments)` instead of `@posts = @user.posts`

_**This comment is about `app/controllers/posts_controller.rb` file**_
Screenshot from 2023-11-14 10-28-54


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MozamelJawad** [comment]
I used the includes in the post folder and index.html.erb file and also checked by gem bullet in the copy of the project, now I added the code in the controller and the result is the same and there is no N+1 problem.

**Review by LionRouge1 — APPROVED** [review]
Hi **Team**, 

# STATUS: APPROVED! 🥇 💯 
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:

done

## Highlights
- Use Capybara gem in `Gemfile` for Integration test :heavy_check_mark: 
- Tested all the features requested in the project requirement :heavy_check_mark: 
- Solve **N+1** problem when fetching all the posts :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
